workflows:
  build:
    name: Build APK with EAS
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      node: 18
    scripts:
      - name: npm install
        script: npm install
      
      - name: Install EAS CLI
        script: npm install -g eas-cli
      
      - name: Build APK
        script: |
          eas build --platform android --profile preview --local --non-interactive --output=./app.apk
      
    artifacts:
      - "app.apk"
